/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import alphabet.*;
import java.awt.Color;
import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.io.File;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nasser
 */
public class alphabet_frame extends javax.swing.JFrame {

    /**
     * Creates new form alphabet_frame
     */
    public alphabet_frame() {
        this.setUndecorated(true);
        initComponents();

        getContentPane().setBackground(new Color(0, 168, 169));  //Color 
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); //FullScreen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        I = new javax.swing.JLabel();
        K = new javax.swing.JLabel();
        O = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        M = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        Q = new javax.swing.JLabel();
        R = new javax.swing.JLabel();
        S = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        U = new javax.swing.JLabel();
        V = new javax.swing.JLabel();
        W = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        Y = new javax.swing.JLabel();
        Z = new javax.swing.JLabel();
        J = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 168, 169));

        jPanel2.setBackground(new java.awt.Color(77, 194, 195));

        A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/A.png"))); // NOI18N
        A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AMouseExited(evt);
            }
        });

        B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/b.png"))); // NOI18N
        B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BMouseExited(evt);
            }
        });

        D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/d.png"))); // NOI18N
        D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DMouseExited(evt);
            }
        });

        C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/c.png"))); // NOI18N
        C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CMouseExited(evt);
            }
        });

        E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/e.png"))); // NOI18N
        E.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EMouseExited(evt);
            }
        });

        H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/h.PNG"))); // NOI18N
        H.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HMouseExited(evt);
            }
        });

        I.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/i.PNG"))); // NOI18N
        I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IMouseExited(evt);
            }
        });

        K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/k.png"))); // NOI18N
        K.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KMouseExited(evt);
            }
        });

        O.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/o.PNG"))); // NOI18N
        O.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OMouseExited(evt);
            }
        });

        F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/f.png"))); // NOI18N
        F.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FMouseExited(evt);
            }
        });

        G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/g.PNG"))); // NOI18N
        G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GMouseExited(evt);
            }
        });

        P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/p.PNG"))); // NOI18N
        P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PMouseExited(evt);
            }
        });

        L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/l.PNG"))); // NOI18N
        L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LMouseExited(evt);
            }
        });

        M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/m.PNG"))); // NOI18N
        M.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MMouseExited(evt);
            }
        });

        N.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/n.PNG"))); // NOI18N
        N.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NMouseExited(evt);
            }
        });

        Q.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/q.PNG"))); // NOI18N
        Q.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QMouseExited(evt);
            }
        });

        R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/r.PNG"))); // NOI18N
        R.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RMouseExited(evt);
            }
        });

        S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/s.PNG"))); // NOI18N
        S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SMouseExited(evt);
            }
        });

        T.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/t.PNG"))); // NOI18N
        T.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TMouseExited(evt);
            }
        });

        U.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/u.PNG"))); // NOI18N
        U.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UMouseExited(evt);
            }
        });

        V.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/v.PNG"))); // NOI18N
        V.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VMouseExited(evt);
            }
        });

        W.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/w.PNG"))); // NOI18N
        W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WMouseExited(evt);
            }
        });

        X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/x.PNG"))); // NOI18N
        X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });

        Y.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/y.PNG"))); // NOI18N
        Y.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                YMouseExited(evt);
            }
        });

        Z.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/z.PNG"))); // NOI18N
        Z.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ZMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ZMouseExited(evt);
            }
        });

        J.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/J.png"))); // NOI18N
        J.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(O)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(P))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(H)
                                .addComponent(A))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(B)
                                .addComponent(I))))
                    .addComponent(V))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(D))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(W)
                                    .addComponent(Q)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(J)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(K, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(R, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(X, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(M)
                    .addComponent(T)
                    .addComponent(Z)
                    .addComponent(F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(G)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(U))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(C, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(D, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(E, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(F, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(G, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(I)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(K, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(H))
                    .addComponent(N)
                    .addComponent(M))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P)
                            .addComponent(O))
                        .addGap(32, 32, 32)
                        .addComponent(V))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(S)
                            .addComponent(T)
                            .addComponent(R)
                            .addComponent(U)
                            .addComponent(Q))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Y)
                                .addComponent(Z)
                                .addComponent(X, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(W)))))
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HELLO KIDS ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Numbers/pallona.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alphabet/abc.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alphapet ");

        jLabel31.setBackground(new java.awt.Color(0, 136, 145));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow-key.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(110, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18))
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    NumberName a = new NumberName();
    private void AMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseEntered
        a.Titel.setText("APPLE");
        a.setLocation(A.getLocationOnScreen().x, A.getLocationOnScreen().y - 95);
        a.setSize(130, 93);
        a.setVisible(true);
    }//GEN-LAST:event_AMouseEntered

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("a.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AMouseClicked

    private void AMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseExited
        a.dispose();
    }//GEN-LAST:event_AMouseExited
    NumberName b = new NumberName();
    private void BMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseEntered
        // TODO add your handling code here:
        b.Titel.setText("BASEBALL");
        b.setLocation(B.getLocationOnScreen().x, B.getLocationOnScreen().y - 95);
        b.setSize(130, 93);

        b.setVisible(true);
    }//GEN-LAST:event_BMouseEntered
    NumberName c = new NumberName();
    private void CMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseEntered
        c.Titel.setText("CLOCK");
        c.setLocation(C.getLocationOnScreen().x, C.getLocationOnScreen().y - 95);
        c.setSize(130, 93);
        c.setVisible(true);

    }//GEN-LAST:event_CMouseEntered

    private void BMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseExited
        b.dispose();
    }//GEN-LAST:event_BMouseExited

    private void CMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseExited
        c.dispose();
    }//GEN-LAST:event_CMouseExited

    private void DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("d.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DMouseClicked
    NumberName d = new NumberName();
    private void DMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseEntered
        d.Titel.setText("DONKEY");
        d.setLocation(D.getLocationOnScreen().x, D.getLocationOnScreen().y - 95);
        d.setSize(130, 93);
        d.setVisible(true);
    }//GEN-LAST:event_DMouseEntered

    private void DMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseExited
        d.dispose();
    }//GEN-LAST:event_DMouseExited

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("e.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_EMouseClicked
    NumberName e = new NumberName();
    private void EMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseEntered
        e.Titel.setText("ELEPHANT");
        e.setLocation(E.getLocationOnScreen().x, E.getLocationOnScreen().y - 95);
        e.setSize(130, 93);
        e.setVisible(true);
    }//GEN-LAST:event_EMouseEntered

    private void EMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseExited
        e.dispose();
    }//GEN-LAST:event_EMouseExited

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("f.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_FMouseClicked
    NumberName f = new NumberName();
    private void FMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseEntered
        f.Titel.setText("FATHER");
        f.setLocation(F.getLocationOnScreen().x, F.getLocationOnScreen().y - 95);
        f.setSize(130, 93);
        f.setVisible(true);
    }//GEN-LAST:event_FMouseEntered

    private void FMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseExited
        f.dispose();
    }//GEN-LAST:event_FMouseExited

    private void GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("g for goat.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_GMouseClicked
    NumberName g = new NumberName();
    private void GMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMouseEntered
        g.Titel.setText("GOAT");
        g.setLocation(G.getLocationOnScreen().x, G.getLocationOnScreen().y - 95);
        g.setSize(130, 93);
        g.setVisible(true);
    }//GEN-LAST:event_GMouseEntered

    private void GMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMouseExited
        g.dispose();
    }//GEN-LAST:event_GMouseExited

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("b.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("c.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CMouseClicked

    private void HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("h.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_HMouseClicked
    NumberName h = new NumberName();
    private void HMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseEntered
        h.Titel.setText("HUNGRY");
        h.setLocation(H.getLocationOnScreen().x, H.getLocationOnScreen().y - 95);
        h.setSize(130, 93);
        h.setVisible(true);

    }//GEN-LAST:event_HMouseEntered

    private void HMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HMouseExited
        h.dispose();
    }//GEN-LAST:event_HMouseExited

    private void IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("i for island.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_IMouseClicked
    NumberName i = new NumberName();
    private void IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMouseEntered
        i.Titel.setText("ISLAND");
        i.setLocation(I.getLocationOnScreen().x, I.getLocationOnScreen().y - 95);
        i.setSize(130, 93);
        i.setVisible(true);
    }//GEN-LAST:event_IMouseEntered

    private void IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMouseExited
        i.dispose();
    }//GEN-LAST:event_IMouseExited

    private void JMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("j for jar.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_JMouseClicked
    NumberName j = new NumberName();
    private void JMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMouseEntered
        j.Titel.setText("JAR");
        j.setLocation(J.getLocationOnScreen().x, J.getLocationOnScreen().y - 95);
        j.setSize(130, 93);
        j.setVisible(true);

    }//GEN-LAST:event_JMouseEntered

    private void JMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMouseExited
        j.dispose();
    }//GEN-LAST:event_JMouseExited

    private void KMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("k for key.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_KMouseClicked
    NumberName k = new NumberName();
    private void KMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseEntered
        k.Titel.setText("KEY");
        k.setLocation(K.getLocationOnScreen().x, K.getLocationOnScreen().y - 95);
        k.setSize(130, 93);
        k.setVisible(true);
    }//GEN-LAST:event_KMouseEntered

    private void KMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KMouseExited
        k.dispose();
    }//GEN-LAST:event_KMouseExited

    private void LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("l for lion.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_LMouseClicked
    NumberName l = new NumberName();
    private void LMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMouseEntered
        l.Titel.setText("LION");
        l.setLocation(L.getLocationOnScreen().x, L.getLocationOnScreen().y - 95);
        l.setSize(130, 93);
        l.setVisible(true);
    }//GEN-LAST:event_LMouseEntered

    private void LMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMouseExited
        l.dispose();
    }//GEN-LAST:event_LMouseExited

    private void MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("m.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_MMouseClicked
    NumberName m = new NumberName();
    private void MMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseEntered
        m.Titel.setText("MONKEY");
        m.setLocation(M.getLocationOnScreen().x, M.getLocationOnScreen().y - 95);
        m.setSize(130, 93);
        m.setVisible(true);
    }//GEN-LAST:event_MMouseEntered

    private void MMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseExited
        m.dispose();
    }//GEN-LAST:event_MMouseExited

    private void NMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("n for name.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_NMouseClicked
    NumberName n = new NumberName();
    private void NMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseEntered
        n.Titel.setText("NAME");
        n.setLocation(N.getLocationOnScreen().x, N.getLocationOnScreen().y - 95);
        n.setSize(130, 93);
        n.setVisible(true);
    }//GEN-LAST:event_NMouseEntered

    private void NMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NMouseExited
        n.dispose();
    }//GEN-LAST:event_NMouseExited

    private void OMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("o for object.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_OMouseClicked
    NumberName o = new NumberName();
    private void OMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseEntered
        o.Titel.setText("OBJECT");
        o.setLocation(O.getLocationOnScreen().x, O.getLocationOnScreen().y - 95);
        o.setSize(130, 93);
        o.setVisible(true);
    }//GEN-LAST:event_OMouseEntered

    private void OMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMouseExited
        o.dispose();
    }//GEN-LAST:event_OMouseExited

    private void PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("p.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_PMouseClicked
    NumberName p = new NumberName();
    private void PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseEntered
        p.Titel.setText("PILLOW");
        p.setLocation(P.getLocationOnScreen().x, P.getLocationOnScreen().y - 95);
        p.setSize(130, 93);
        p.setVisible(true);
    }//GEN-LAST:event_PMouseEntered

    private void PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseExited
        p.dispose();
    }//GEN-LAST:event_PMouseExited

    private void QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("q.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_QMouseClicked
    NumberName q = new NumberName();
    private void QMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QMouseEntered
        q.Titel.setText("QUESTION");
        q.setLocation(Q.getLocationOnScreen().x, Q.getLocationOnScreen().y - 95);
        q.setSize(130, 93);
        q.setVisible(true);
    }//GEN-LAST:event_QMouseEntered

    private void QMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QMouseExited
        q.dispose();
    }//GEN-LAST:event_QMouseExited

    private void RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("r.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_RMouseClicked
    NumberName r = new NumberName();
    private void RMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMouseEntered
        r.Titel.setText("RABBIT");
        r.setLocation(R.getLocationOnScreen().x, R.getLocationOnScreen().y - 95);
        r.setSize(130, 93);
        r.setVisible(true);
    }//GEN-LAST:event_RMouseEntered

    private void RMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RMouseExited
        r.dispose();
    }//GEN-LAST:event_RMouseExited

    private void SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("s.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_SMouseClicked
    NumberName s = new NumberName();
    private void SMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseEntered
        s.Titel.setText("SUPER_MAN");
        s.setLocation(S.getLocationOnScreen().x, S.getLocationOnScreen().y - 95);
        s.setSize(130, 93);
        s.setVisible(true);
    }//GEN-LAST:event_SMouseEntered

    private void SMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SMouseExited
        s.dispose();
    }//GEN-LAST:event_SMouseExited

    private void TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("t.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_TMouseClicked
    NumberName t = new NumberName();
    private void TMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseEntered
        t.Titel.setText("TELEPHONE");
        t.setLocation(T.getLocationOnScreen().x, T.getLocationOnScreen().y - 95);
        t.setSize(130, 93);
        t.setVisible(true);
    }//GEN-LAST:event_TMouseEntered

    private void TMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseExited
        t.dispose();
    }//GEN-LAST:event_TMouseExited

    private void UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("u for umbrella.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UMouseClicked
    NumberName u = new NumberName();
    private void UMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMouseEntered
        u.Titel.setText("UMBRELLA");
        u.setLocation(U.getLocationOnScreen().x, U.getLocationOnScreen().y - 95);
        u.setSize(130, 93);
        u.setVisible(true);
    }//GEN-LAST:event_UMouseEntered

    private void UMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UMouseExited
        u.dispose();
    }//GEN-LAST:event_UMouseExited

    private void VMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("v for van.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_VMouseClicked
    NumberName v = new NumberName();
    private void VMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VMouseEntered
        v.Titel.setText("VAN");
        v.setLocation(V.getLocationOnScreen().x, V.getLocationOnScreen().y - 95);
        v.setSize(130, 93);
        v.setVisible(true);
    }//GEN-LAST:event_VMouseEntered

    private void VMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VMouseExited
        v.dispose();
    }//GEN-LAST:event_VMouseExited

    private void WMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("w for work.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_WMouseClicked
    NumberName w = new NumberName();
    private void WMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WMouseEntered
        w.Titel.setText("WORK");
        w.setLocation(W.getLocationOnScreen().x, W.getLocationOnScreen().y - 95);
        w.setSize(130, 93);
        w.setVisible(true);
    }//GEN-LAST:event_WMouseEntered

    private void WMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WMouseExited
        w.dispose();
    }//GEN-LAST:event_WMouseExited

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("x for x-rays.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_XMouseClicked
    NumberName x = new NumberName();
    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        x.Titel.setText("X-RAYS");
        x.setLocation(X.getLocationOnScreen().x, X.getLocationOnScreen().y - 95);
        x.setSize(130, 93);
        x.setVisible(true);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        x.dispose();
    }//GEN-LAST:event_XMouseExited

    private void YMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("y.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_YMouseClicked
    NumberName y = new NumberName();
    private void YMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YMouseEntered
        y.Titel.setText("YOUGRT");
        y.setLocation(Y.getLocationOnScreen().x, Y.getLocationOnScreen().y - 95);
        y.setSize(130, 93);
        y.setVisible(true);
    }//GEN-LAST:event_YMouseEntered

    private void YMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YMouseExited
        y.dispose();
    }//GEN-LAST:event_YMouseExited

    private void ZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZMouseClicked
        try {

            JFXPanel h = new JFXPanel();
            String uri = new File("z.mp3").toURI().toString();
            new MediaPlayer(new Media(uri)).play();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ZMouseClicked
    NumberName z = new NumberName();
    private void ZMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZMouseEntered
        z.Titel.setText("ZEBRA");
        z.setLocation(Z.getLocationOnScreen().x, Z.getLocationOnScreen().y - 95);
        z.setSize(130, 93);
        z.setVisible(true);
    }//GEN-LAST:event_ZMouseEntered

    private void ZMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZMouseExited
        z.dispose();
    }//GEN-LAST:event_ZMouseExited

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        dispose();
        
      
        

    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alphabet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alphabet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alphabet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alphabet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alphabet_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel G;
    private javax.swing.JLabel H;
    private javax.swing.JLabel I;
    private javax.swing.JLabel J;
    private javax.swing.JLabel K;
    private javax.swing.JLabel L;
    private javax.swing.JLabel M;
    private javax.swing.JLabel N;
    private javax.swing.JLabel O;
    private javax.swing.JLabel P;
    private javax.swing.JLabel Q;
    private javax.swing.JLabel R;
    private javax.swing.JLabel S;
    private javax.swing.JLabel T;
    private javax.swing.JLabel U;
    private javax.swing.JLabel V;
    private javax.swing.JLabel W;
    private javax.swing.JLabel X;
    private javax.swing.JLabel Y;
    private javax.swing.JLabel Z;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
